### ISSUE TITLE
Correct the "About" section 

### ISSUE THREAD

**Issue by wasup-yash** [zjunior-infra/zJunior#77]
Correct the word `"Thier"` to `Their`.

**Comment by Mahmoudgalalz** [comment]
you can start workin on that if you would like, there's a bunch of typos in our site

**Comment by wasup-yash** [comment]
Yes i can work on the typos but regarding this issue, i think this can only be corrected by the repo owner as the about section is created when repo is created.

**Comment by Mahmoudgalalz** [comment]
you still can create a PR fixing this issue

**Comment by wasup-yash** [comment]
> you still can create a PR fixing this issue

Ok i will try to do it, and in meantime you can also create issues that you need help with as there are no active issues to work on for folks.

**Comment by wasup-yash** [comment]
@Mahmoudgalalz hey as far as i made the changes in my about section of the repo it cannot be count as commit as it is `about repo` section and it will be changed as owner right and i am here referencing this github repo about section not website about section.

**Comment by Mahmoudgalalz** [comment]
> > you still can create a PR fixing this issue
> 
> Ok i will try to do it, and in meantime you can also create issues that you need help with as there are no active issues to work on for folks.

I will be doing that, sooner, Thanks

**Comment by Mahmoudgalalz** [comment]
> 

yeah you can still suggest more info and fixing the typos

send your PR with your charming thoughts 
here's the repo in the about Section which called 'README of the org' this would help me to understand you clearly
https://github.com/zjunior-infra/.github/tree/main/profile

I will close this issue as it's not belongs to this repo

Thanks @wasup-yash
